# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e5027f1477ece64dded2fcf2ab88e29d373f6440b953b245528956a66cbb730db102f1e3c468d513969a6aacc95282b8c23a3db0c37eec53526cecbc35075cf5

test:
  secret_key_base: 79ac0c23ceadf6a62c1c204d3641a91853540f75bd07a33d4887107ccf741230ccc14de52a47f4e4ff697f6fe3d84c30ed18043b748a9a56fa5b0bdd00a86c25

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
